server:
  servlet:
    context-path: /seller
  port: 8082

rpc:
  client:
    url:  http://localhost:8081/manager/
    basePackage: com.imooc.api

logging:
    level:
      com.googlecode.jsonrpc4j: debug

spring:
  cache:
    type: hazelcast